<?php
/**
 * CloudServerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  NETZFABRIK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NETZFABRIK API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: info@netzfabrik.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace NETZFABRIK\Test\Api;

use \NETZFABRIK\Configuration;
use \NETZFABRIK\ApiException;
use \NETZFABRIK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CloudServerApiTest Class Doc Comment
 *
 * @category Class
 * @package  NETZFABRIK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CloudServerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteServer
     *
     * Delete server.
     *
     */
    public function testDeleteServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getServer
     *
     * Get server.
     *
     */
    public function testGetServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getServerStatistics
     *
     * Get server statistics.
     *
     */
    public function testGetServerStatistics()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getServers
     *
     * Get servers.
     *
     */
    public function testGetServers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restartServer
     *
     * Restart server.
     *
     */
    public function testRestartServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for shutdownServer
     *
     * Shutdown server.
     *
     */
    public function testShutdownServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for startServer
     *
     * Start server.
     *
     */
    public function testStartServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for stopServer
     *
     * Stop server.
     *
     */
    public function testStopServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
