<?php
/**
 * ColocationApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  NETZFABRIK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NETZFABRIK API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: info@netzfabrik.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace NETZFABRIK\Test\Api;

use \NETZFABRIK\Configuration;
use \NETZFABRIK\ApiException;
use \NETZFABRIK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ColocationApiTest Class Doc Comment
 *
 * @category Class
 * @package  NETZFABRIK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ColocationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addColocation
     *
     * Add a colocation.
     *
     */
    public function testAddColocation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getColocation
     *
     * Get a colocation.
     *
     */
    public function testGetColocation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getColocationInterconnections
     *
     * Get the interconnections of a colocation.
     *
     */
    public function testGetColocationInterconnections()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getColocationPowerFeeds
     *
     * Get the power feeds of a colocation.
     *
     */
    public function testGetColocationPowerFeeds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
