<?php
/**
 * NetworkApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  NETZFABRIK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NETZFABRIK API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: info@netzfabrik.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace NETZFABRIK\Test\Api;

use \NETZFABRIK\Configuration;
use \NETZFABRIK\ApiException;
use \NETZFABRIK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NetworkApiTest Class Doc Comment
 *
 * @category Class
 * @package  NETZFABRIK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NetworkApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for attachNetworkToServer
     *
     * Add network to server.
     *
     */
    public function testAttachNetworkToServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createNetwork
     *
     * Create network.
     *
     */
    public function testCreateNetwork()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNetwork
     *
     * Delete network.
     *
     */
    public function testDeleteNetwork()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for detachNetworkFromServer
     *
     * Detach network from server.
     *
     */
    public function testDetachNetworkFromServer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNetwork
     *
     * Get network.
     *
     */
    public function testGetNetwork()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
